version: "3.3"
services:

  # database
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"

  # database
  mysql:
    image: mysql:8.0
    ports:
    # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  # php-fpm
  php:
    build: ./php
    ports:
      - "9000"
    volumes:
      - ./app:/var/www/html
      # Your php.ini
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/php-fpm.conf:/usr/local/etc/php/php-fpm.conf:ro
      - ./php/php-fpm.d:/usr/local/etc/php/php-fpm.d
      - ./php/hosts:/etc/hosts
    # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
    entrypoint: ["php", "/var/www/html/swoole.php"]
    links:
      - mysql:mysql
      - redis:redis


  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      # app
      - ./app:/usr/share/nginx/html
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # certificates
      #- ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
      #- ./nginx/ca/server.key/:/etc/nginx/server.key:ro
    links:
      - php

